version: "3.8"

services:
  redis:
    container_name: redis-cache
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  postgres-client:
    image: postgres:latest
    container_name: postgres-client
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=client_db
    ports:
      - "5433:5432"

  postgres-transaction:
    image: postgres:latest
    container_name: postgres-transaction
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transaction_db
    ports:
      - "5432:5432"

volumes:
  redis:
